### ISSUE TITLE
SCRIPT ERROR: @tropic-business/server.lua:95: attempt to index a nil value (local 'Player')

### ISSUE THREAD

**Issue by Duguayster** [TropicGalxy/tropic-business#1]
Runing QBCore Version 1.2.6

When players connect to the server I get that message in the console:
[script:tropic-busine] SCRIPT ERROR: @tropic-business/server.lua:95: attempt to index a nil value (local 'Player')

And when I'm in the game and try to buy a business:
[script:tropic-busine] SCRIPT ERROR: @tropic-business/server.lua:45: attempt to index a nil value (global 'player')
[script:tropic-busine] SCRIPT ERROR: @tropic-business/server.lua:74: attempt to index a nil value (global 'player')

**Comment by TropicGalxy** [comment]
ill see what i can do

**Comment by TropicGalxy** [comment]
error fixed!
